import type { BridgeDO } from "./bridge-do.ts";
import type { BridgeMcp } from "./mcp.ts";

// Worker bindings. Normally generated by `wrangler types`; declared here so the
// project type-checks without running wrangler.
declare global {
  interface Env {
    BRIDGE_TOKEN: string;
    BRIDGE_DO: DurableObjectNamespace<BridgeDO>;
    BRIDGE_MCP: DurableObjectNamespace<BridgeMcp>;
  }
}

export {};
