export type HelpTopic = "task-spec" | "result" | "events" | "concepts" | "forge";

export const HELP_TOPICS: HelpTopic[] = ["task-spec", "result", "events", "concepts", "forge"];

function lines(items: string[]): string {
  return `${items.join("\n")}\n`;
}

export function topLevelHelp(): string {
  return lines([
    "orch: daemonless multi-agent orchestrator",
    "",
    "Commands:",
    "  orch               Overview: active runs + pending actions as runnable commands (--json for agents;",
    "                     items idle > --attention-days (14) age out; merged-branch mrs auto-archive)",
    "  orch verdict       Aggregate one thread's verdicts and suggest a decision (--wait blocks)",
    "  orch wait          Block until the next run in a thread needs attention (wait-any)",
    "  orch run create    Start one headless worker run for an MR task",
    "  orch run list      List local runs for an MR",
    "  orch search        Regex-search repo run files and mail event diagnostics",
    "  orch usage         Summarize token usage by run, thread, or day",
    "  orch cross-review  Review one diff/run in parallel with several agents",
    "  orch fanout        Run one task across several agents (any result role)",
    "  orch investigate   Read-only research/analysis (defaults to gemini-3.1-pro)",
    "  orch events tail   Print a run's local events.jsonl (--native: provider progress)",
    "  orch result        Print a run's local result.json",
    "  orch status        Read local run status for an MR",
    "  orch decision      Record accept/rework/close; sweep batch-acks the backlog",
    "  orch mirror        Mirror a local run result summary to a PR/MR comment",
    "  orch mirror sync   Send queued outbox comments to a PR/MR",
    "  orch chatgpt-bridge  Deploy + connect the read-only ChatGPT bridge (Cloudflare Worker)",
    "  orch handoff-pro   Hand off full repo context to a tool-less model (e.g. gpt-5.5-pro)",
    "  orch mail          Queue, locally deliver, and import signed orch mail events",
    "  orch mailctl       Drive orch from IMAP/SMTP mail: init, poll, watch, status, reply, ack, attachments",
    "  orch workspace     Add or list project workspaces for mail routing",
    "  orch update        Self-update to the latest GitHub release (--check to only compare)",
    "",
    "Quickstart:",
    "  orch run create --mr 123 --role implementer --agent codex --tag impl-a --worktree . --task task.md",
    "  orch run list --mr 123 --worktree .",
    "  orch search 'timeout|permission' --worktree .",
    "  orch usage thread --thread 123 --json",
    "  orch events tail --run impl-a-20260619T120000Z-abc123 --mr 123 -n 20",
    "  orch result --run impl-a-20260619T120000Z-abc123 --mr 123",
    "  orch decision accept --mr 123 --run impl-a-20260619T120000Z-abc123 --reason \"reviewed\"",
    "  orch mirror sync --mr 123",
    "  orch status --mr 123 --json",
    "  cat ${XDG_STATE_HOME:-$HOME/.local/state}/orch/<repo_key>/mrs/123/runs/<run_id>/result.json",
    "",
    "Use:",
    "  orch <command> --help",
    "  orch help <topic>",
    "",
    "Topics:",
    "  task-spec | result | events | concepts | forge",
  ]);
}

export function runCreateHelp(): string {
  return lines([
    "orch run create: start a supervised headless worker run",
    "",
    "Usage:",
    "  orch run create --role <role> --agent <agent> [--mr <id>] [--tag <tag>] [--worktree <path>] [--task <file>] [flags]",
    "",
    "Flags:",
    "  --mr <id>                 MR or task id used under the local state directory; when omitted it is",
    "                            resolved from an 'MR: <id-or-url>' line in the task's leading header block,",
    "                            then a GitLab merge-request / github.com pull URL in the task text, then",
    "                            the current branch (GitHub Enterprise hosts: use the MR: header)",
    "  --role <role>             Result role: implementer, reviewer, verifier, controller, or researcher (required)",
    "  --agent <agent>           Headless provider driver: codex, claude, pi, or omp (required)",
    "                            omp = oh-my-pi; defaults to google-antigravity/gemini-3.1-pro and",
    "                            falls back to zenmux/anthropic/claude-fable-5 then openai-codex/gpt-5.6",
    "                            when the active model's quota/rate limit is exhausted",
    "  Read-only roles are sandboxed per provider: reviewer launches the worker without",
    "  write access (claude plan mode / codex read-only / pi and omp read tools).",
    "  Controller is Claude-only and launches with an allowed-tool whitelist for",
    "  orch shell commands plus read-only file inspection tools.",
    "  Researcher (architect) is read-only and delivers a recommendation",
    "  (orch.result/researcher/v1), never code. claude runs fable at xhigh effort",
    "  with a whitelist (jina/tvly CLIs + web tools); codex defaults to gpt-5.6-sol",
    "  at xhigh reasoning with native web search on; omp rides its gemini chain",
    "  with read-only tools (repo-internal research, no web). pi is not supported.",
    "  claude picks model/effort by role: reviewer opus/high (deep critique),",
    "  implementer sonnet/medium, verifier sonnet/low (mechanical checks),",
    "  researcher fable/xhigh, controller sonnet/medium; --model overrides.",
    "  --tag <tag>               Human-readable run id prefix; defaults to --role",
    "  --model <ref>             Provider model override passed through to supported drivers",
    "  --worktree <path>         Git worktree where the worker runs; defaults to the current directory",
    "  --task <file>             Task spec file passed to the worker; omitted means an empty task",
    "  --resume-from <run_id>    Continue that run's provider session with this task: the worker keeps",
    "                            its context (files read, reasoning, prompt cache) instead of starting",
    "                            from zero. Inherits agent/role/mr/worktree/model from the prior run",
    "                            unless overridden; conflicts with --agent (sessions are not portable)",
    "                            and the --session-* flags. Typical use: dispatch the rework run against",
    "                            the reviewed implementer run",
    "  --idempotency-key <key>   Reuse an existing run for the same key; default includes mr, tag, task, session, and model settings",
    "  --retry                   Create a new run even when --idempotency-key already exists",
    "  --allow-dirty             Acknowledge dirty write-role worktree and suppress the warning",
    "  --timeout-sec <seconds>   Worker timeout; defaults to 3600 for reviewer, 14400 otherwise",
    "  --session-mode <mode>     Provider session policy: ephemeral, fresh_persistent, or resume_exact",
    "  --session-name <name>     Provider display name when supported (Claude/Pi; Codex rejects fresh names)",
    "  --session-id <id>         Provider session id; only valid with --session-mode resume_exact",
    "  --dry-run                Resolve and print the planned run without writing state or spawning",
    "  --json                   With --dry-run, emit the dry-run plan as JSON instead of text",
    "  --help                    Show this help",
    "",
    "Example:",
    "  orch run create --mr 123 --role implementer --agent codex --tag impl-a --worktree . --task task.md --timeout-sec 3600",
    "  orch run create --resume-from impl-a-20260707T010000-abc123 --tag rework-a --task rework.md",
  ]);
}

export function runListHelp(): string {
  return lines([
    "orch run list: list local runs for an MR",
    "",
    "Usage:",
    "  orch run list [--mr <id>] [--worktree <path>] [--json]",
    "",
    "Flags:",
    "  --mr <id>             MR or task id whose local runs should be listed; omitted lists all MRs in this repo",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --json                Print a machine-readable array instead of an aligned table",
    "  --help                Show this help",
    "",
    "Output fields:",
    "  run_id, mr, role, agent, tag, state, started_at, exit_code",
    "",
    "Examples:",
    "  orch run list --mr 123 --worktree .",
    "  orch run list --worktree . --json    # all MRs in this repo",
  ]);
}

export function searchHelp(): string {
  return lines([
    "orch search: regex-search local repo runs and mail diagnostics",
    "",
    "Usage:",
    "  orch search <regex> [--mr <id>] [--run <run_id>] [--thread <id>] [--worktree <path>] [--json]",
    "",
    "Flags:",
    "  --mr <id>             Restrict run-file scanning to one MR/task id",
    "  --run <run_id>        Restrict run-file scanning to one run; --mr disambiguates duplicate ids",
    "  --thread <id>         Scan one mail thread's mail-events.jsonl; by default mail is scanned only",
    "                        for an unscoped repo search, or when --thread is explicit",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --json                Print stable machine-readable hits",
    "  --help                Show this help",
    "",
    "Scanned files:",
    "  result.json, events.jsonl, native.jsonl, artifacts/*.{txt,log,patch}, and mail-events.jsonl",
    "",
    "JSON shape:",
    "  { schema: \"orch.search/v1\", repo_key, worktree, pattern, scope, searched_files, hits[] }",
    "  hit: { source, mr, run_id, thread, file, path, line, context }",
    "",
    "Examples:",
    "  orch search 'ToolFailed|timeout' --worktree .",
    "  orch search 'permission denied' --mr 123 --json",
    "  orch search 'task.assigned' --thread review-123",
  ]);
}

export function usageHelp(): string {
  return lines([
    "orch usage: summarize token usage from native provider events",
    "",
    "Usage:",
    "  orch usage run --run <run_id> [--mr <id>] [--worktree <path>] [--json]",
    "  orch usage thread --thread <id> [--worktree <path>] [--json]",
    "  orch usage daily [--days N] [--worktree <path>] [--json]",
    "",
    "Flags:",
    "  --run <run_id>        Run id for usage run (required)",
    "  --mr <id>             Disambiguate --run, or alias for --thread in usage thread",
    "  --thread <id>         Thread / MR whose runs should be aggregated",
    "  --days <N>            Daily window in UTC run-start dates; defaults to 7",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --json                Print stable machine-readable output",
    "  --help                Show this help",
    "",
    "Missing data:",
    "  Missing token events are reported as has_token_data=false with usage=null.",
    "  estimated_cost_usd is always null until a real pricing table exists.",
    "  unpriced_models lists model names observed in spec.json or native.jsonl.",
    "",
    "JSON shapes:",
    "  run:    { schema: \"orch.usage/run/v1\", repo_key, mr, run_id, has_token_data, usage, estimated_cost_usd, unpriced_models, usage_events, source_file }",
    "  thread: { schema: \"orch.usage/thread/v1\", repo_key, thread, run_count, runs_with_token_data, missing_runs, has_token_data, usage, estimated_cost_usd, unpriced_models, runs[] }",
    "  daily:  { schema: \"orch.usage/daily/v1\", repo_key, days, since, until, buckets[] }",
    "",
    "Examples:",
    "  orch usage run --run impl-a-20260707T010000-abc123 --json",
    "  orch usage thread --thread review-123 --json",
    "  orch usage daily --days 14 --json",
  ]);
}

export function statusHelp(): string {
  return lines([
    "orch status: read local status for all runs in an MR",
    "",
    "Usage:",
    "  orch status [--mr <id>] [--json] [--worktree <path>]",
    "",
    "Flags:",
    "  --mr <id>             MR or task id whose local runs should be read; omitted shows all MRs in this repo",
    "  --json                Print machine-readable JSON instead of a tabular summary",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --help                Show this help",
    "",
    "Example:",
    "  orch status --mr 123 --json --worktree .",
  ]);
}

export function verdictHelp(): string {
  return lines([
    "orch verdict: aggregate one thread's run verdicts and suggest a decision",
    "",
    "Usage:",
    "  orch verdict --thread <id> [--wait] [--wait-sec <n>] [--json] [--worktree <path>]",
    "",
    "Flags:",
    "  --thread <id>         Thread / mr whose runs should be aggregated (--mr works too)",
    "  --wait                Block until every run in the thread reaches a terminal state",
    "  --wait-sec <n>        Wait budget in seconds; defaults to 900",
    "  --json                Machine-readable output (runs, suggestion, runnable actions)",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --help                Show this help",
    "",
    "The suggestion is one of accept, rework, inspect, pending, or reap; every",
    "pending action is printed as a runnable orch command line.",
    "",
    "Example:",
    "  orch cross-review --thread review-42 --task review.md",
    "  orch verdict --thread review-42 --wait",
  ]);
}

export function waitHelp(): string {
  return lines([
    "orch wait: block until the next run in a thread needs attention (wait-any)",
    "",
    "Usage:",
    "  orch wait --thread <id> [--timeout-sec <n>] [--worktree <path>]",
    "",
    "Flags:",
    "  --thread <id>         Thread / mr to watch (--mr works too)",
    "  --timeout-sec <n>     Give up after this many seconds; defaults to 900",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --help                Show this help",
    "",
    "Returns one JSON event and exits:",
    "  run_terminal   a run finished and has no decision yet (suggested_argv included)",
    "  stale          a run's supervisor died (suggests orch run reap)",
    "  settled        every run is terminal and decided — nothing left to wait for",
    "",
    "A recorded decision acts as the ack: decided runs are never returned again,",
    "so a controller loops `orch wait` -> handle -> `orch wait` until settled.",
  ]);
}

export function eventsTailHelp(): string {
  return lines([
    "orch events tail: print a run's local events.jsonl",
    "",
    "Usage:",
    "  orch events tail --run <run_id> [--mr <id>] [--worktree <path>] [-n <lines>] [--native] [-f]",
    "  orch events tail -f [--all] [--mr <id>] [--worktree <path>] [-n <lines>] [--native]",
    "",
    "Flags:",
    "  --run <run_id>        Local orch run id to read; omitted with -f follows every active run",
    "  --mr <id>             MR or task id containing the run; omitted scans this repo's local MR state",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  -n <lines>            Print only the last N lines; omitted prints the whole file",
    "  --native              Render native.jsonl as normalized provider progress events instead",
    "                        (kinds: session, assistant, tool_use, tool_result, usage, final, raw)",
    "  -f, --follow          Stream new lines as workers append them. With --run, exits once the",
    "                        run is terminal (or stale) and drained. Without --run, multiplexes",
    "                        every active run (tail-style ==> mr/run <== headers), picks up runs",
    "                        created while following, and runs until Ctrl-C; -n replays that many",
    "                        lines of context per run, otherwise streaming starts at the tail",
    "  --all                 With -f and no --run: follow every repo under the orch state root,",
    "                        not just the current worktree's (headers gain a repo: prefix)",
    "  --help                Show this help",
    "",
    "Examples:",
    "  orch events tail --run impl-a-20260619T120000Z-abc123 --mr 123",
    "  orch events tail --run impl-a-20260619T120000Z-abc123 --worktree . -n 20",
    "  orch events tail --run impl-a-20260619T120000Z-abc123 --native -n 20",
    "  orch events tail --run impl-a-20260619T120000Z-abc123 --native -f",
    "  orch events tail -f --native",
    "  orch events tail -f --all",
  ]);
}

export function resultCommandHelp(): string {
  return lines([
    "orch result: print a run's local result.json",
    "",
    "Usage:",
    "  orch result --run <run_id> [--mr <id>] [--worktree <path>] [--wait] [--json]",
    "",
    "Flags:",
    "  --run <run_id>        Local orch run id to read (required)",
    "  --mr <id>             MR or task id containing the run; omitted scans this repo's local MR state",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --wait                Block until the run reaches a terminal state, then print the result",
    "  --wait-sec <seconds>  Max wait for --wait; defaults to 900",
    "  --json                Print result.json exactly as stored",
    "  --help                Show this help",
    "",
    "Human output:",
    "  Prints schema, verdict, and summary. Reviewer results include findings and suggested tests;",
    "  verifier results include commands and acceptance; implementer results include changed_files and tests.",
    "  When schema extraction failed, the worker's raw final message is kept in the run dir as result.raw.md.",
    "",
    "Examples:",
    "  orch result --run impl-a-20260619T120000Z-abc123 --mr 123",
    "  orch result --run impl-a-20260619T120000Z-abc123 --worktree . --json",
  ]);
}

export function decisionHelp(): string {
  return lines([
    "orch decision: record a controller decision for one run",
    "",
    "Usage:",
    "  orch decision accept|rework|close --mr <id> --run <run_id> [--reason <text>] [--worktree <path>]",
    "  orch decision sweep [--mr <id>] [--execute] [--worktree <path>]",
    "",
    "Flags:",
    "  --mr <id>             Pull request or merge request id for the local state directory (required)",
    "  --run <run_id>        Local orch run id being accepted or sent back for rework (required)",
    "  --reason <text>       Optional human decision reason included in decision.json and the queued comment",
    "  --execute             (sweep) record the planned decisions; without it sweep only prints the plan",
    "  --worktree <path>     Git worktree used to derive repo_key; defaults to the current directory",
    "  --help                Show this help",
    "",
    "Behavior:",
    "  Writes runs/<run_id>/decision.json locally.",
    "  accept/rework queue a comment payload in outbox/pending/; close is a pure ack",
    "  (stop tracking this run) and queues nothing. Use orch mirror sync to dry-run",
    "  or send queued outbox comments.",
    "  sweep batch-acks every undecided terminal run using the overview's rubric:",
    "  good verdict + 0 blocking -> accept, bad verdict -> rework, failed/timeout or",
    "  missing result -> close. Sweep never queues mirror comments.",
    "",
    "Examples:",
    "  orch decision accept --mr 123 --run impl-a-20260619T120000Z-abc123 --reason \"reviewed\"",
    "  orch decision close --mr 123 --run impl-a-20260619T120000Z-abc123 --reason obsolete",
    "  orch decision sweep            # print the backlog-clearing plan",
    "  orch decision sweep --execute  # record it",
  ]);
}

export function updateHelp(): string {
  return lines([
    "orch update: self-update to the latest GitHub release",
    "",
    "Usage:",
    "  orch update [--check]",
    "",
    "Flags:",
    "  --check     Only compare the running version against the latest release tag",
    "  --help      Show this help",
    "",
    "Behavior:",
    "  Queries the latest release of github.com/yanyaoer/orch-cli, downloads the",
    "  binary for this platform, probes it with --version, then atomically",
    "  replaces the running executable. Already up to date is a no-op.",
    "  Only works for the compiled binary; a source checkout should run",
    "  git pull && bun run install:local instead.",
    "",
    "Install (first time):",
    "  curl -fsSL https://raw.githubusercontent.com/yanyaoer/orch-cli/main/install.sh | sh",
  ]);
}

export function mirrorHelp(): string {
  return lines([
    "orch mirror: mirror a local run result or sync queued outbox comments to a PR/MR",
    "",
    "Usage:",
    "  orch mirror --mr <id> [--run <run_id>] [--worktree <path>] [--execute]",
    "  orch mirror sync --mr <id> [--worktree <path>] [--execute]",
    "",
    "Flags:",
    "  --mr <id>             Pull request or merge request id to comment on (required)",
    "  --run <run_id>        Local orch run id to mirror; defaults to the newest run for the MR",
    "  --worktree <path>     Git worktree used to derive repo_key and remote; defaults to the current directory",
    "  --execute             Execute the gh/glab command. Omitted means dry-run only",
    "  --help                Show this help",
    "",
    "Modes:",
    "  Without sync, mirrors one local run result directly and preserves the old dry-run output contract.",
    "  With sync, reads outbox/pending/*.json and sends queued comment payloads; successful sends move to outbox/sent/.",
    "",
    "Examples:",
    "  orch mirror --mr 123 --run impl-a-20260619T120000Z-abc123",
    "  orch mirror --mr 123 --run impl-a-20260619T120000Z-abc123 --execute",
    "  orch mirror sync --mr 123",
    "  orch mirror sync --mr 123 --execute",
    "  orch mirror --mr 123 --worktree /path/to/repo",
  ]);
}

export function mirrorSyncHelp(): string {
  return lines([
    "orch mirror sync: send queued outbox comments to a PR/MR",
    "",
    "Usage:",
    "  orch mirror sync --mr <id> [--worktree <path>] [--execute]",
    "",
    "Flags:",
    "  --mr <id>             Pull request or merge request id whose outbox should be synced (required)",
    "  --worktree <path>     Git worktree used to derive repo_key and remote; defaults to the current directory",
    "  --execute             Execute the gh/glab commands. Omitted means dry-run only",
    "  --help                Show this help",
    "",
    "Behavior:",
    "  Dry-run prints each gh/glab argv and does not touch the network.",
    "  --execute sends pending comments one by one.",
    "  Successful sends move from outbox/pending/ to outbox/sent/.",
    "  Failed sends stay in outbox/pending/ and local run or decision state is unchanged.",
    "",
    "Examples:",
    "  orch mirror sync --mr 123",
    "  orch mirror sync --mr 123 --execute",
  ]);
}

export function workspaceHelp(): string {
  return lines([
    "orch workspace: manage project workspaces used by mail routing",
    "",
    "Usage:",
    "  orch workspace add --id <id> --path <dir>",
    "  orch workspace list",
    "",
    "Behavior:",
    "  Stores project directories in ${XDG_CONFIG_HOME:-$HOME/.config}/orch/config.json.",
    "  Mail tasks can reference a workspace with --workspace <id>.",
    "",
    "Examples:",
    "  orch workspace add --id orch-cli --path .",
    "  orch mail submit --thread th_plan --workspace orch-cli --task task.md",
  ]);
}

export function mailHelp(): string {
  return lines([
    "orch mail: local signed-mail message bus for orch task dispatch",
    "",
    "Usage:",
    "  orch mail agent defaults",
    "  orch mail agent bind --id <id> --address <addr> --provider <name> --role <role> [--work-mode <mode>] [--session-mode <mode>] [--auto-invite]",
    "  orch mail agent list",
    "  orch mail submit --thread <id> [--mr <id>] --workspace <id> --task <file>",
    "  orch mail route --thread <id> [--worktree <path>]",
    "  orch mail claim --thread <id> --agent <id> [--mr <id>] [--dry-run] [--worktree <path>]",
    "  orch mail assign --thread <id> --role <role> --task <file> [--to-agent <id>] [--parent-event <event>]",
    "  orch mail reply result --thread <id> --run <run_id> --from-agent <id> [--to-agent <id>] [--parent-event <event>]",
    "  orch mail compose decision --thread <id> --run <run_id> [--from-agent <id>] [--to-agent <id>] [--worktree <path>]",
    "  orch mail deliver-local|import|list|path --thread <id> [flags]; orch mail neomutt [--json]; orch mail sendmail [--thread <id>]",
    "",
    "Behavior:",
    "  agent defaults configures orch-router plus codex/claude/pi local mailboxes with roles and work modes.",
    "  submit sends a signed router task to orch-router@local.orch; route first expands imported router tasks into implementer mail only.",
    "  after an implementer replies with result.submitted, route fans that concrete result out to reviewer and verifier mail.",
    "  claim atomically leases assigned mail tasks and starts orch run create; use --dry-run to preview without launching a provider.",
    "  assign selects auto-invite agents by role, or a single --to-agent, and queues task.requested mail.",
    "  reply result sends a signed result.submitted mail back into the same thread.",
    "  deliver-local copies queued .eml files into inbox/raw, mirrors them into a Maildir at mail/threads/<id>/maildir/, and moves them to outbox/sent/.",
    "  neomutt opens NeoMutt by default; without --thread it reads every configured workspace and thread.",
    "  NeoMutt send is wired to orch mail sendmail: messages to orch-router@local.orch become signed router tasks, then route+deliver locally.",
    "  Pass --json to print the generated rc/maildir/mailboxes instead of launching NeoMutt.",
    "  Invalid, unsigned, wrong-thread, or wrong-repo messages are written to inbox/quarantine/ and never trigger runs.",
    "  Successful non-dry-run claims are acked under claims/*.claim.json and mail-claimed.json; failed starts are nacked for retry.",
    "  NeoMutt macros: F5 deliver, F6 import selected, F7 route+deliver, F10 assign, F11 reply result.",
    "",
    "Examples:",
    "  orch mail agent defaults",
    "  orch workspace add --id orch-cli --path .",
    "  orch mail submit --thread th_plan --mr 123 --workspace orch-cli --task task.md",
    "  RAW=$(orch mail deliver-local --thread th_plan | bun -e 'const p=JSON.parse(await Bun.stdin.text()); console.log(p.delivered[0]?.to ?? \"\")')",
    "  orch mail import --thread th_plan --file \"$RAW\"",
    "  orch mail route --thread th_plan",
    "  orch mail claim --thread th_plan --agent codex-implementer --dry-run",
    "  orch mail neomutt",
    "  orch mail neomutt --json",
  ]);
}

export function mailctlHelp(): string {
  return lines([
    "orch mailctl: IMAP/SMTP mail controller for orch",
    "",
    "Usage:",
    "  orch mailctl init    --user <email> --imap-host <host> --smtp-host <host> --allow <sender>... --workspace <id> [flags]",
    "  orch mailctl poll    [--json] [--dry-run]",
    "  orch mailctl watch",
    "  orch mailctl status  [--json]",
    "  orch mailctl reply   --thread em-<id> --report-key <key> (--body <text>|--body-file <file>) [--dry-run]",
    "  orch mailctl ack     --thread em-<id> --attention <id>",
    "  orch mailctl guidance --thread em-<id> [--json]",
    "  orch mailctl attachments [--thread em-<id>] [--json]",
    "  orch mailctl attachment show --id att-<id>",
    "  orch mailctl attachment promote --id att-<id> [--dest <dir>] [--json]",
    "",
    "Init flags:",
    "  --password-cmd <argv-json>       JSON argv array executed directly, without a shell, to read the account password",
    "  --trusted-authserv-id <id>       Authentication-Results authserv-id to trust; defaults to the IMAP host's domain",
    "                                  and should be confirmed with the mail provider",
    "  --smtp-mode implicit|starttls    SMTP submit mode; default implicit",
    "  --imap-port <n>                  IMAP port; default 993",
    "  --smtp-port <n>                  SMTP port; default 465 or 587 for starttls",
    "  --smtp-from <email>              Envelope/header From for replies; default --user",
    "  --subject-token <token>          Extra shared token that must appear in inbound subjects",
    "",
    "Behavior:",
    "  poll is the main contract for cron/launchd: one bounded ingest + reconcile cycle.",
    "  watch is only a foreground convenience loop around INBOX IDLE plus periodic reconcile.",
    "  reply --dry-run prints the RFC822 message and does not contact SMTP.",
    "  ack atomically moves controller/attention/<id>.json to done/<id>.json and clears the T1 trigger.",
    "  guidance lists the thread's unacked inbound instructions for a controller.",
    "  Attachments from accepted mail are quarantined under mail-control state, never the worktree or the prompt.",
    "  attachment show prints safe text types (txt/log/md/patch/diff/json/csv) to stdout; promote copies any stored payload to a file.",
    "  status shows rejected_* marker counts for the last 7 days so a locked-out sender is visible without reading audit.jsonl.",
    "",
    "Security posture:",
    "  --allow checks From:, which is weak authentication and is not sufficient by itself.",
    "  By default mailctl requires a trusted authserv-id Authentication-Results header with DKIM and DMARC pass plus domain alignment.",
    "  Mail rejected by sender/auth/token/loop checks leaves a rejected_* marker and audit entry instead of disappearing silently.",
    "  --subject-token adds another shared-secret layer on top of Authentication-Results.",
    "  mailctl selects INBOX only; do not point it at All Mail or Sent.",
    "",
    "Examples:",
    "  orch mailctl init --user bot@example.com --imap-host imap.example.com --smtp-host smtp.example.com --allow owner@example.com --workspace orch-cli --password-cmd '[\"security\",\"find-generic-password\",\"-w\",\"-s\",\"orch-mail\"]'",
    "  orch mailctl poll --json",
    "  orch mailctl guidance --thread em-abc123 --json",
    "  orch mailctl ack --thread em-abc123 --attention deadbeef1234",
    "  orch mailctl reply --thread em-abc123 --report-key settled:0 --body-file report.md --dry-run",
  ]);
}

export function topicHelp(topic: HelpTopic): string {
  switch (topic) {
    case "task-spec":
      return lines([
        "orch help task-spec",
        "",
        "--task points to the instruction file for one worker run. The file is captured into the run spec so the worker can be replayed and audited without reading external docs.",
        "",
        "A useful task file includes:",
        "  - Goal: the concrete change, review, or verification to perform",
        "  - Role: implementer writes code, reviewer audits an existing run, verifier executes checks",
        "  - Agent: codex, claude, pi, or omp, the headless provider driver that will execute the task",
        "    (omp = oh-my-pi: gemini-3.1-pro by default with quota fallback to claude-fable-5, then gpt-5.6)",
        "  - Worktree: the absolute or relative repository checkout where commands should run",
        "  - Constraints: inline the relevant ADR/spec excerpts that bound the solution",
        "  - Acceptance: explicit checks the worker must claim or prove",
        "",
        "Inline constraints because task content is captured into spec.json and runs must be replayable without reading external docs.",
        "",
        "Worker contract:",
        "  - The worker must finish by producing result.json in the run directory.",
        "  - result.json must use the schema for its role: orch.result/implementer/v1, reviewer/v1, verifier/v1, controller/v1, or researcher/v1.",
        "  - The supervisor validates required fields before marking the run done.",
        "",
        "Example task.md:",
        "  Role: implementer",
        "  Worktree: /path/to/repo",
        "  Goal: add progressive help to the orch CLI.",
        "  Acceptance: build succeeds, tests pass, help topics print useful command guidance.",
      ]);
    case "result":
      return lines([
        "orch help result",
        "",
        "Every run ends with result.json. The schema field identifies the role-specific shape.",
        "",
        "implementer: orch.result/implementer/v1",
        "  Key fields: verdict, summary, base_sha, head_sha, changed_files[], tests[], acceptance[], risks[], rollback",
        "  tests[] items include cmd, exit_code, summary",
        "  acceptance[] items include id, status, evidence",
        "",
        "reviewer: orch.result/reviewer/v1",
        "  Key fields: verdict, reviews_run_id, blocking_findings[], non_blocking_findings[], suggested_tests[]",
        "  verdict is approve or request_changes",
        "  blocking findings include id, severity, file, body",
        "",
        "verifier: orch.result/verifier/v1",
        "  Key fields: verdict, verifies_run_id, commands[], acceptance[]",
        "  verdict is pass or fail",
        "  commands[] items include cmd, exit_code, summary",
        "",
        "researcher: orch.result/researcher/v1",
        "  Key fields: verdict, summary, recommendation, alternatives[], sources[], open_questions[], risks[]",
        "  verdict is completed or failed",
        "",
        "Main controllers should read result.json for decisions; provider-native output is retained separately for debugging.",
      ]);
    case "events":
      return lines([
        "orch help events",
        "",
        "Orch events are the normalized local event stream for a run. They live at:",
        "  ${XDG_STATE_HOME:-$HOME/.local/state}/orch/<repo_key>/mrs/<mr>/runs/<run_id>/events.jsonl",
        "",
        "Each line is one JSON object with type, seq, and ts. MVP event types are created, starting, running, heartbeat, done, failed, and timeout.",
        "",
        "Provider-native JSON or text is stored separately in native.jsonl, stdout.log, and stderr.log. Do not treat provider-native records as orch events.",
        "",
        "orch events tail --native renders native.jsonl as normalized progress events (kinds: session, assistant, tool_use, tool_result, usage, final, raw) for observability. They describe what the worker is doing; run state authority stays with events.jsonl and status.json.",
        "",
        "MR-facing progress messages may use an orch-evt prefix as a mirror, but the local events.jsonl file is the source a controller should poll.",
      ]);
    case "concepts":
      return lines([
        "orch help concepts",
        "",
        "Role permissions:",
        "  implementer is the only write role and takes the worktree lock; rework/debug",
        "  follow-ups are implementer runs (dispatch with --resume-from and a tag).",
        "  reviewer, researcher, and verifier inspect immutable artifacts and do not take the worktree write lock.",
        "  researcher additionally reaches the web (jina/tvly CLIs on claude, native web search on codex) but never writes code.",
        "",
        "Run state machine:",
        "  created -> starting -> running -> done",
        "  exceptional terminal states: failed, timeout, cancelled, stale",
        "",
        "State directory layout:",
        "  ${XDG_STATE_HOME:-$HOME/.local/state}/orch/<repo_key>/mrs/<mr>/runs/<run_id>/",
        "  Shorthand: ${XDG_STATE_HOME:-~/.local/state}/orch/<repo_key>/mrs/<mr>/runs/<run_id>/",
        "  Important files: spec.json, spec.sha256, status.json, events.jsonl, native.jsonl, stdout.log, stderr.log, result.json, artifacts/",
        "  MR outbox: ${XDG_STATE_HOME:-~/.local/state}/orch/<repo_key>/mrs/<mr>/outbox/{pending,sent}/",
        "",
        "Outbox:",
        "  Decision and queued mirror payloads are written locally first under outbox/pending/.",
        "  orch mirror sync is dry-run by default; --execute sends via gh/glab and moves successful payloads to outbox/sent/.",
        "  Failed sends remain pending and do not change local run or decision state.",
        "",
        "Idempotency and locks:",
        "  A1: repeating run create with the same idempotency key returns the existing run instead of dispatching another worker.",
        "  A2: only one write-role run may hold a given worktree lock at a time.",
        "  The default idempotency key is mr<id>:<tag>:<task_sha>:session-<fingerprint>, where the fingerprint includes provider session and model settings.",
        "",
        "Provider sessions:",
        "  Defaults do not resume the most recent provider session. Claude/Codex start fresh persistent runs; Pi and omp stay ephemeral.",
        "  Use --session-name for supported provider display names, and --session-mode resume_exact --session-id <id> for exact resume only.",
        "  orch never generates provider latest-session flags such as --continue or --last.",
        "",
        "Forge adapter:",
        "  orch can derive GitHub or GitLab from the repository remote and mirror local result summaries with gh or glab.",
      ]);
    case "forge":
      return lines([
        "orch help forge",
        "",
        "The forge adapter chooses the PR/MR CLI from the current repository remote:",
        "  github.com remotes use gh and GitHub pull requests.",
        "  gitlab.com and self-hosted non-GitHub git hosts use glab and GitLab merge requests.",
        "  missing, local, or unparsable remotes are forge=none and mirror is skipped.",
        "",
        "Safety:",
        "  orch mirror and orch mirror sync are dry-run by default. They print the gh/glab argv that would be executed and do not touch the network.",
        "  Pass --execute to run the planned forge command for real.",
        "",
        "Examples:",
        "  orch mirror --mr 123 --run impl-a-20260619T120000Z-abc123",
        "  orch mirror --mr 123 --run impl-a-20260619T120000Z-abc123 --execute",
        "  orch mirror sync --mr 123",
        "  orch mirror sync --mr 123 --execute",
      ]);
  }
}

export function unknownTopicHelp(topic: string): string {
  return lines([
    `unknown help topic: ${topic}`,
    "",
    "Available topics:",
    `  ${HELP_TOPICS.join(" | ")}`,
    "",
    "Use:",
    "  orch help <topic>",
  ]);
}

export function chatgptBridgeHelp(): string {
  return lines([
    "orch chatgpt-bridge: deploy + connect the read-only ChatGPT bridge in one step",
    "",
    "Usage:",
    "  orch chatgpt-bridge [--worktree <path>] [--redeploy] [--no-connect] [--bridge-dir <path>]",
    "  orch chatgpt-bridge --url <ws(s)://host/ws> --token <T> [--worktree <path>] [--no-connect]",
    "",
    "Managed mode (no --url/--token):",
    "  On first run it deploys the Cloudflare Worker via wrangler, generates a strong",
    "  BRIDGE_TOKEN, derives the MCP/WebSocket URLs, and saves them to the config below.",
    "  Later runs reuse the saved Worker. It then registers the worktree and connects.",
    "  Requires wrangler on PATH and `wrangler login` (Cloudflare auth).",
    "",
    "Direct mode (--url + --token):",
    "  Connects to an already-running Worker (e.g. local `wrangler dev`) without",
    "  deploying or overwriting the saved Worker. Useful for local development.",
    "",
    "Flags:",
    "  --worktree <path>   Worktree the remote may read; defaults to the current directory",
    "  --redeploy          Force a fresh wrangler deploy + new token (managed mode)",
    "  --no-connect        Deploy/register and print the mcp_url, but do not connect",
    "  --bridge-dir <path> Worker source dir; defaults to the chatgpt-bridge dir in the repo",
    "  --url <url>         Direct mode: Worker WebSocket endpoint, e.g. wss://<worker>.workers.dev/ws",
    "  --token <token>     Direct mode: shared secret matching the Worker's BRIDGE_TOKEN",
    "  --help              Show this help",
    "",
    "Config: ${XDG_CONFIG_HOME:-$HOME/.config}/orch/chatgpt-bridge.json (mode 0600; holds token).",
    "Paste the printed mcp_url into ChatGPT → Settings → Apps → Developer mode → Create.",
    "",
    "The agent dials out over WebSocket (no inbound port / tunnel) and serves read-only",
    "tools scoped to the worktree: open_workspace, read, search, show_changes.",
    "",
    "Examples:",
    "  orch chatgpt-bridge --worktree .                 # deploy (first run) + connect",
    "  orch chatgpt-bridge --no-connect                 # deploy + print mcp_url only",
    "  orch chatgpt-bridge --url ws://localhost:8787/ws --token test   # local dev",
  ]);
}

export function handoffProHelp(): string {
  return lines([
    "orch handoff-pro: hand off full repo context to a model that cannot call tools",
    "",
    "Usage:",
    "  orch handoff-pro [--worktree <path>] [--path <file>]... [--glob <pat>]... [flags]",
    "",
    "Why:",
    "  A normal sub-agent handoff is terse: the agent has tools and reads the repo",
    "  itself. handoff-pro is the opposite — strong models that reason WITHOUT tools",
    "  (e.g. ChatGPT Pro / gpt-5.5-pro) cannot read your repo, so this packs a full",
    "  snapshot (tree, status, diff, key + changed file contents) into one markdown",
    "  blob you paste in for review/planning. Execute the resulting plan with",
    "  `orch run create --agent codex|pi --task <plan>`.",
    "",
    "Flags:",
    "  --worktree <path>        Repo to snapshot; defaults to the current directory",
    "  --path <file>            Include this file (repeatable)",
    "  --glob <pat>             Include files matching this glob (repeatable)",
    "  --title <t>              Bundle title heading",
    "  --out <file>             Output path; defaults to",
    "                           ${XDG_STATE_HOME:-$HOME/.local/state}/orch/<repo_key>/handoffs/context-<ts>.md",
    "  --copy                   Also copy the markdown to the clipboard (macOS pbcopy)",
    "  --no-diff                Skip the git diff section",
    "  --no-important-files     Do not auto-include important root files (README, package.json, ...)",
    "  --no-changed-files       Do not auto-include git-changed files",
    "  --max-files <n>          Max files embedded (default 24)",
    "  --max-file-bytes <n>     Max bytes per embedded file (default 60000)",
    "  --max-diff-bytes <n>     Max bytes of git diff (default 80000)",
    "  --max-total-bytes <n>    Max total bundle bytes before truncation (default 700000)",
    "  --help                   Show this help",
    "",
    "Safety:",
    "  All paths pass the bridge path guard; .env, private keys, .git, and node_modules",
    "  are always excluded, and obvious inline secrets are redacted. Output lives under",
    "  XDG_STATE (user-private), never inside the worktree.",
    "",
    "Examples:",
    "  orch handoff-pro --worktree . --copy",
    "  orch handoff-pro --path src/orch.ts --glob 'src/**/*.ts' --copy",
  ]);
}

export function fanoutHelp(): string {
  return lines([
    "orch cross-review / fanout / investigate: fan one task across several agents via mail",
    "",
    "These route through the mail layer: the --thread carries the mr and workspace",
    "context (no --mr needed). Each resolves one task per target agent, reusing",
    "the same thread/role/agent/task hash when present, then claims only those",
    "resolved events; follow the runs with orch status / orch result. Requires",
    "configured mail agents (run 'orch mail agent defaults' once).",
    "",
    "Usage:",
    "  orch cross-review --thread <id> --task <file> [--to-agent <id>]... [--workspace <id>] [flags]",
    "  orch fanout --thread <id> --role <role> --task <file> [--to-agent <id>]... [flags]",
    "  orch investigate --thread <id> --task <file> [--to-agent <id>]... [flags]",
    "",
    "Commands:",
    "  cross-review   Reviewer role; default agents: claude-reviewer, omp-reviewer",
    "  fanout         Any result role via --role (required); agents auto-invited for that role",
    "                 (--role researcher fans to codex-researcher + claude-researcher by default)",
    "  investigate    Researcher role, read-only research; default agents: omp-researcher, claude-researcher",
    "",
    "Flags:",
    "  --thread <id>             Mail thread that scopes the runs and supplies the mr (required)",
    "  --role <role>             fanout only: implementer, reviewer, verifier, controller, or researcher (required)",
    "  --to-agent <id>           Mail agent id, repeatable; overrides the command's default roster",
    "  --task <file>             Task spec file published to every target agent",
    "  --workspace <id>          Workspace whose path is the worktree; defaults to the current directory",
    "  --mr <id>                 Optional explicit mr; defaults to the thread id",
    "  --model <ref>             Provider model override forwarded to every spawned run",
    "                            (re-running a thread with a different model needs a new task or --retry on the run)",
    "  --timeout-sec <seconds>   Worker timeout; defaults to 3600 for reviewer, 14400 otherwise",
    "  --allow-dirty             Forwarded to run create for write-role runs",
    "  --dry-run                 Print the resolved agents without publishing or running",
    "  --auto                    cross-review only: wait for this fan-out's runs, record the",
    "                            unambiguous decisions (approve→accept, blocking→rework), and",
    "                            queue ONE merged MR comment; fallback/failed runs are surfaced,",
    "                            never auto-decided",
    "  --execute                 With --auto: actually post the merged comment (default: dry-run)",
    "  --wait-sec <seconds>      With --auto: max wait for runs to settle (default 900)",
    "  --help                    Show this help",
    "",
    "Examples:",
    "  orch cross-review --thread review-123 --task review.md",
    "  orch cross-review --thread 3823 --task review.md --auto --execute",
    "  orch fanout --thread verify-123 --role verifier --to-agent pi-verifier --task verify.md",
    "  orch investigate --thread research-1 --task question.md",
  ]);
}

export function runHelp(): string {
  return lines([
    "orch run commands:",
    "  orch run create    Start one headless worker run for an MR task",
    "  orch run list      List local runs for an MR (dead-pid runs show as 'stale?')",
    "  orch run reap      Persist 'stale' for non-terminal runs whose supervisor pid is gone",
    "",
    "Use:",
    "  orch run create --help",
    "  orch run list --help",
    "  orch run reap [--mr <id>] [--worktree <path>]   # omitted --mr reaps across all MRs in this repo",
  ]);
}
